### ISSUE TITLE
Since we're using ES2015, we should also use classes

### ISSUE THREAD

**Issue by pakastin** [redom/nodom#12]
For example here: https://github.com/pakastin/nodom/blob/master/lib/htmlelement.js#L31

Classes are supported since Node v4, so they should be ok to use:
http://node.green

**Comment by jirutka** [comment]
I just noticed this issue. So you’re okay with refactoring the sources to use `class`es?

**Comment by pakastin** [comment]
Not necessary, but if it makes sense..
